### ISSUE TITLE
esp_deep_sleep.h <--- cannot open source file "esp_deep_sleep.h"

### ISSUE THREAD

**Issue by jjdsantos** [kripthor/io433#3]
Hi kripthor. I clone your repository and try to compile, but there are some errors.
e.g. cannot open source file "esp_deep_sleep.h"

Can you help me, please? Thanks a lot!
Julio

 *  Executing task: platformio run 

Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (5.2.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20005.220925 (2.0.5) 
 - tool-esptoolpy @ 1.40201.0 (4.2.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 35 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Button2 @ 1.6.5
|-- WiFi @ 2.0.0
|-- SmartRC-CC1101-Driver-Lib @ 2.5.6
|   |-- SPI @ 2.0.0
|-- TFT_eSPI @ 2.3.64
|   |-- SPI @ 2.0.0
|   |-- SPIFFS @ 2.0.0
|   |   |-- FS @ 2.0.0
|   |-- FS @ 2.0.0
|-- FS @ 2.0.0
|-- SPIFFS @ 2.0.0
|   |-- FS @ 2.0.0
Building in release mode
Compiling .pio/build/esp32dev/src/main.cpp.o
Archiving .pio/build/esp32dev/lib19b/libButton2.a
Indexing .pio/build/esp32dev/lib19b/libButton2.a
In file included from lib/TFT_eSPI/User_Setup_Select.h:53,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setups/Setup25_TTGO_T_Display.h:17: warning: "TFT_CS" redefined
 #define TFT_CS              5
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:22,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setup.h:159: note: this is the location of the previous definition
 #define TFT_CS   PIN_D8  // Chip select control pin D8
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:53,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setups/Setup25_TTGO_T_Display.h:18: warning: "TFT_DC" redefined
 #define TFT_DC              16
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:22,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setup.h:160: note: this is the location of the previous definition
 #define TFT_DC   PIN_D3  // Data Command control pin
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:53,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setups/Setup25_TTGO_T_Display.h:19: warning: "TFT_RST" redefined
 #define TFT_RST             23
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:22,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setup.h:161: note: this is the location of the previous definition
 #define TFT_RST  PIN_D4  // Reset pin (could connect to NodeMCU RST, see next line)
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:53,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setups/Setup25_TTGO_T_Display.h:36: warning: "SPI_FREQUENCY" redefined
   #define SPI_FREQUENCY  40000000   // Maximum for ILI9341
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:22,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setup.h:322: note: this is the location of the previous definition
 #define SPI_FREQUENCY  27000000
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:53,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setups/Setup25_TTGO_T_Display.h:39: warning: "SPI_READ_FREQUENCY" redefined
 #define SPI_READ_FREQUENCY  6000000 // 6 MHz is the maximum SPI read speed for the ST7789V
 
In file included from lib/TFT_eSPI/User_Setup_Select.h:22,
                 from lib/TFT_eSPI/TFT_eSPI.h:39,
                 from src/SimpleMenuNav.h:4,
                 from src/main.cpp:3:
lib/TFT_eSPI/User_Setup.h:328: note: this is the location of the previous definition
 #define SPI_READ_FREQUENCY  20000000
 
Compiling .pio/build/esp32dev/lib216/WiFi/WiFiSTA.cpp.o
Compiling .pio/build/esp32dev/lib216/WiFi/WiFiScan.cpp.o
Compiling .pio/build/esp32dev/lib216/WiFi/WiFiServer.cpp.o
Compiling .pio/build/esp32dev/lib216/WiFi/WiFiUdp.cpp.o
In file included from src/main.cpp:3:
src/SimpleMenuNav.h:9: warning: "LONGCLICK_MS" redefined
 #define LONGCLICK_MS 300
 
In file included from src/SimpleMenuNav.h:2,
                 from src/main.cpp:3:
.pio/libdeps/esp32dev/Button2/src/Button2.h:21: note: this is the location of the previous definition
 #define LONGCLICK_MS 200
 
src/main.cpp:5:10: fatal error: esp_deep_sleep.h: No such file or directory

************************************************************************
* Looking for esp_deep_sleep.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_deep_sleep.h"
* Web  > https://registry.platformio.org/search?q=header:esp_deep_sleep.h
*
************************************************************************

 #include "esp_deep_sleep.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio/build/esp32dev/lib4e4/SPI/SPI.cpp.o
Compiling .pio/build/esp32dev/lib7da/SmartRC-CC1101-Driver-Lib/ELECHOUSE_CC1101_SRC_DRV.cpp.o
*** [.pio/build/esp32dev/src/main.cpp.o] Error 1
=============================================================== [FAILED] Took 3.04 seconds ===============================================================

 *  The terminal process "platformio 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by vreabernardo** [comment]
esp_deep_sleep.h was [deprecated in IDF](https://github.com/espressif/esp-idf/commit/d2acf1ce77a2883e519ef57da5ff3e45bb0d6bbe#diff-d559a707898ac2219e52770f63377ce0R26) in favor of esp_sleep.h which has [already been updated in Arduino](https://github.com/espressif/arduino-esp32/commit/39fb8c30440a4abd5fe0e2c87609ba6798ae8013)

Just replace:
 `#include "esp_deep_sleep.h"`
For: 
`#include "esp_sleep.h"`

and the functions:
`esp_deep_sleep_pd_config()`
For:
`esp_sleep_pd_config()`

and it should work

**Comment by jjdsantos** [comment]
Thank you for your explanation and suggestions, @vreabernardo .

Thank you so much for your support and help, @kripthor .

I think that we can close this issue. Best, Julio

**Comment by kripthor** [comment]
Hi @vreabernardo! I've noticed you have fixed the issue and made a pull request. At the same time, I was working on the issue with Julio and also fixed the issue. Many thanks anyway! :)
